#!/bin/bash

# arquivo NCM_SH4
#cabecalho 
sed -r -n '1s/","/"#"/pg' NCM_SH_T.csv | cut -d# -f6-10 > ncm_sh4
#corpo 
sed -r -n '2,$s/","/"#"/pg' NCM_SH_T.csv | cut -d# -f6-10 | sort | uniq >> ncm_sh4

# arquivo NCM_SH2
#cabecalho 
sed -r -n '1s/","/"#"/pg' NCM_SH_T.csv | cut -d# -f10-14 > ncm_sh2
#corpo 
sed -r -n '2,$s/","/"#"/pg' NCM_SH_T.csv | cut -d# -f10-14 | sort | uniq >> ncm_sh2

# arquivo NCM_SECROM
#cabecalho 
sed -r -n '1s/","/"#"/pg' NCM_SH_T.csv | cut -d# -f14-17 > ncm_secrom
#corpo 
sed -r -n '2,$s/","/"#"/pg' NCM_SH_T.csv | cut -d# -f14-17 | sort | uniq >> ncm_secrom














